var AppConstants = {
  ACTION_GET_STATS:     "ACTION_GET_STATS",

  EVENT_NEW_DATA:       "EVENT_NEW_DATA",

  STATUS_FETCHING:      "STATUS_FETCHING",
  STATUS_FETCHING_OFF:  "STATUS_SEARCH",
  STATUS_ERROR_OCCURED: "STATUS_ERROR_OCCURED"
};

module.exports = AppConstants;
